<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <title>Animal List</title>

</head>

<body>
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="index.html">Main</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="about.html">About</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="details.html">Polar Bear</a>
    </li>
</ul>

<h1>Animals of Artic</h1>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<h3>1. Emperor Penguins</h3>
<img src="img/penguin.jpg" class="img-fluid" alt="">
<p><b>Where they can be found:</b> Antartica <br>
    <b>Diet:</b>krill, squid, fish, and crustaceans <br>
    <b>Weight/Height:</b> 42-100 lbs/ 3.7-3.8 ft. <br>
    <b>Fun Fact:</b> Largest penguins in the world. <br>
</p>



<h3>2. Polar Bear</h3>
<img src="img/bear.jpg" class="img-fluid" alt="">
<a href="details.html" class="btn btn-primary" role="button" data-bs-toggle="button">More about Polar Bears</a>
<p><b>Where they can be found:</b> Canada, Greenland, Norway, Russia, and Alaska <br>
    <b>Diet:</b> Seals, beluga whales, narwhals, walrus<br>
    <b>Weight/Height:</b> 900-1,600 lbs/ 6.6-8.2 ft long  <br>
    <b>Fun Fact:</b> Biggest type of bear species worldwide. <br>
</p>

<h3>3. Artic Fox</h3>
<img src="img/fox.jpg" class="img-fluid" alt="">
<p><b>Where they can be found: </b>Europe, Asia, North America, Greenland, Iceland <br>
    <b>Diet:</b> small mammals, birds, and fish<br>
    <b>Weight/Height:</b> 7.7-21 lbs/ 43 in long <br>
    <b>Fun Fact:</b> They are monogamous. <br>
</p>

<h3>4. Greenland Shark</h3>
<img src="img/shark.jpg" class="img-fluid" alt="">
<p><b>Where they can be found:</b> Artic and North Atlantic Oceans <br>
    <b>Diet:</b> fish, seals, squid, and seabirds <br>
    <b>Weight/Height:</b> 1,500-2,200 lbs/ 23 ft long <br>
    <b>Fun Fact:</b> Can live up to around 250-500 years. <br>
</p>

<h3>5. Reindeer</h3>
<img src="img/reindeer.jpg" class="img-fluid" alt="">
<p><b>Where they can be found:</b> Greenland, Scandinavia, Russia, Alaska and Canada <br>
    <b>Diet:</b> mosses, herbs, ferns, grasses, and trees <br>
    <b>Weight/Height:</b> 240-365 lb / 2.2-4.9 ft tall <br>
    <b>Fun Fact:</b> The only deer species to have hair completely covering thier noses. <br>
</p>


</body>
</html>